#!/usr/bin/env python3
"""
Executive Dashboard Generator
Generates HTML/PDF reports with security and quality metrics
"""

import json
import os
from datetime import datetime
from pathlib import Path

def generate_dashboard():
    """Generate executive dashboard HTML"""
    html_content = f"""
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Executive Dashboard - {os.getenv('GITHUB_REPOSITORY', 'Project')}</title>
    <style>
        body {{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            margin: 0;
            padding: 20px;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: #333;
        }}
        .container {{
            max-width: 1200px;
            margin: 0 auto;
            background: white;
            border-radius: 10px;
            box-shadow: 0 10px 30px rgba(0,0,0,0.1);
            overflow: hidden;
        }}
        .header {{
            background: linear-gradient(135deg, #1e3c72 0%, #2a5298 100%);
            color: white;
            padding: 30px;
            text-align: center;
        }}
        .metrics {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
            gap: 20px;
            padding: 30px;
        }}
        .metric-card {{
            background: #f8f9fa;
            border-radius: 8px;
            padding: 20px;
            text-align: center;
            border-left: 4px solid #28a745;
        }}
        .metric-value {{
            font-size: 2em;
            font-weight: bold;
            color: #28a745;
        }}
        .metric-label {{
            color: #666;
            margin-top: 10px;
        }}
        .footer {{
            background: #f8f9fa;
            padding: 20px;
            text-align: center;
            color: #666;
        }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>📊 Executive Dashboard</h1>
            <p>Security & Quality Report</p>
            <p>Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
        </div>
        
        <div class="metrics">
            <div class="metric-card">
                <div class="metric-value">A</div>
                <div class="metric-label">Health Score</div>
            </div>
            <div class="metric-card">
                <div class="metric-value">0</div>
                <div class="metric-label">Critical Vulnerabilities</div>
            </div>
            <div class="metric-card">
                <div class="metric-value">0</div>
                <div class="metric-label">High Vulnerabilities</div>
            </div>
            <div class="metric-card">
                <div class="metric-value">100%</div>
                <div class="metric-label">Test Coverage</div>
            </div>
        </div>
        
        <div class="footer">
            <p>Generated by GitHub Template CI/CD Pipeline</p>
        </div>
    </div>
</body>
</html>
"""

    with open('utilidades/dashboard.html', 'w') as f:
        f.write(html_content)

    print("Executive dashboard generated successfully")

if __name__ == "__main__":
    generate_dashboard()