#!/bin/bash -e
DEFAULT_REGISTRY="ghcr.io"
CTX_REGISTRY=""
CTX_REPO="grs89/Web_Metrics_Collector"
RAW_REGISTRY="${CTX_REGISTRY:-$DEFAULT_REGISTRY}"
RAW_REPO="${CTX_REPO}"

IMAGE_NAME_LC="${RAW_REGISTRY,,}/${RAW_REPO,,}"
IMAGE_NAME_LC="${IMAGE_NAME_LC// /}"
IMAGE_NAME_LC="${IMAGE_NAME_LC//$'\n'/}"
IMAGE_NAME_LC="${IMAGE_NAME_LC//$'\r'/}"
echo "image_name_lc=${IMAGE_NAME_LC}"
