name: Terraform Security Scan (PDF Reports)

on:
  workflow_call:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  terraform-security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # ---------- INSTALL TOOLS ----------
      - name: Install Security Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install checkov
          
          curl -s https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/html.tpl -o trivy.tpl
          curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash

      # ---------- INSTALL PLAYWRIGHT ----------
      - name: Install Playwright
        run: |
          npm init -y
          npm install playwright
          npx playwright install chromium

      # ---------- TRIVY ----------
      - name: Trivy IaC Scan
        continue-on-error: true
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          scan-ref: '.'
          format: 'template'
          template: 'trivy.tpl'
          output: 'trivy.html'
          severity: 'LOW,MEDIUM,HIGH,CRITICAL'

      - name: Trivy IaC Scan (JSON)
        continue-on-error: true
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          scan-ref: '.'
          format: 'json'
          output: 'trivy.json'
          severity: 'LOW,MEDIUM,HIGH,CRITICAL'

      # ---------- TFSEC ----------
      - name: tfsec Scan
        continue-on-error: true
        run: |
          tfsec . --format html --out tfsec.html || true
          tfsec . --format json --out tfsec.json || true

      # ---------- CHECKOV ----------
      - name: Checkov Scan
        continue-on-error: true
        run: |
          checkov -d . --framework terraform -o html > checkov.html || true
          checkov -d . --framework terraform -o json > checkov.json || true

      # ---------- HTML → PDF ----------
      - name: Convert HTML to PDF
        if: always()
        run: |
          cat <<'EOF' > render.js
          const { chromium } = require('playwright');
          const fs = require('fs');

          async function parseTrivy(file) {
            if (!fs.existsSync(file)) return { counts: { CRITICAL: 0, HIGH: 0, MEDIUM: 0, LOW: 0 }, findings: [] };
            try {
              const data = JSON.parse(fs.readFileSync(file, 'utf8'));
              let counts = { CRITICAL: 0, HIGH: 0, MEDIUM: 0, LOW: 0 };
              let findings = [];
              const results = data.Results || [];
              results.forEach(r => {
                (r.Misconfigurations || []).forEach(m => {
                  const sev = m.Severity.toUpperCase();
                  if (counts[sev] !== undefined) counts[sev]++;
                  findings.push({
                    tool: 'Trivy',
                    resource: m.ID || 'N/A',
                    severity: sev,
                    description: m.Title || m.Message || 'No description'
                  });
                });
              });
              return { counts, findings };
            } catch (e) { return { counts: { CRITICAL: 0, HIGH: 0, MEDIUM: 0, LOW: 0 }, findings: [] }; }
          }

          async function parseTfsec(file) {
            if (!fs.existsSync(file)) return { counts: { CRITICAL: 0, HIGH: 0, MEDIUM: 0, LOW: 0 }, findings: [] };
            try {
              const data = JSON.parse(fs.readFileSync(file, 'utf8'));
              let counts = { CRITICAL: 0, HIGH: 0, MEDIUM: 0, LOW: 0 };
              let findings = [];
              (data.results || []).forEach(r => {
                const sev = r.severity.toUpperCase();
                if (counts[sev] !== undefined) counts[sev]++;
                findings.push({
                  tool: 'tfsec',
                  resource: r.resource || 'N/A',
                  severity: sev,
                  description: r.description || 'No description'
                });
              });
              return { counts, findings };
            } catch (e) { return { counts: { CRITICAL: 0, HIGH: 0, MEDIUM: 0, LOW: 0 }, findings: [] }; }
          }

          async function parseCheckov(file) {
            if (!fs.existsSync(file)) return { counts: { CRITICAL: 0, HIGH: 0, MEDIUM: 0, LOW: 0 }, findings: [] };
            try {
              const data = JSON.parse(fs.readFileSync(file, 'utf8'));
              let counts = { CRITICAL: 0, HIGH: 0, MEDIUM: 0, LOW: 0 };
              let findings = [];
              const results = Array.isArray(data) ? data : [data];
              results.forEach(res => {
                 (res.results?.failed_checks || []).forEach(c => {
                   const sev = (c.severity || 'MEDIUM').toUpperCase();
                   if (counts[sev] !== undefined) counts[sev]++;
                   findings.push({
                     tool: 'Checkov',
                     resource: c.resource || 'N/A',
                     severity: sev,
                     description: c.check_name || 'No description'
                   });
                 });
              });
              return { counts, findings };
            } catch (e) { return { counts: { CRITICAL: 0, HIGH: 0, MEDIUM: 0, LOW: 0 }, findings: [] }; }
          }

          (async () => {
            const trivy = await parseTrivy('trivy.json');
            const tfsec = await parseTfsec('tfsec.json');
            const checkov = await parseCheckov('checkov.json');

            const tools = [
              { name: 'Trivy IaC', data: trivy },
              { name: 'tfsec', data: tfsec },
              { name: 'Checkov', data: checkov }
            ];

            const severityPriority = { 'CRITICAL': 0, 'HIGH': 1, 'MEDIUM': 2, 'LOW': 3 };

            let html = `
            <!DOCTYPE html>
            <html>
            <head>
              <meta charset="UTF-8">
              <style>
                body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 40px; color: #333; background-color: #f9f9f9; }
                h1 { color: #2c3e50; text-align: center; margin-bottom: 30px; border-bottom: 2px solid #3498db; padding-bottom: 15px; }
                .dashboard { display: flex; flex-wrap: wrap; justify-content: center; gap: 20px; margin-bottom: 40px; }
                .card { background: white; border-radius: 12px; padding: 25px; width: 280px; box-shadow: 0 8px 16px rgba(0,0,0,0.1); border: 1px solid #eee; }
                .card h2 { margin-top: 0; font-size: 1.4em; color: #2c3e50; border-bottom: 2px solid #f1f1f1; padding-bottom: 12px; margin-bottom: 20px; }
                .severity { display: flex; justify-content: space-between; margin: 12px 0; padding-bottom: 8px; border-bottom: 1px dashed #eee; }
                .severity:last-child { border-bottom: none; }
                .label { font-weight: 500; color: #7f8c8d; }
                .val { font-weight: bold; font-size: 1.1em; }
                .CRITICAL { color: #c0392b; font-weight: bold; }
                .HIGH { color: #e67e22; font-weight: bold; }
                .MEDIUM { color: #f1c40f; font-weight: bold; }
                .LOW { color: #27ae60; font-weight: bold; }
                .timestamp { text-align: center; color: #95a5a6; margin-top: 60px; font-size: 0.9em; font-style: italic; }
                .summary-table { width: 100%; border-collapse: collapse; margin-top: 20px; background: white; box-shadow: 0 4px 8px rgba(0,0,0,0.05); }
                .summary-table th, .summary-table td { padding: 12px; text-align: left; border-bottom: 1px solid #eee; font-size: 0.9em; }
                .summary-table th { background-color: #3498db; color: white; }
                .tool-header { background-color: #ecf0f1; font-weight: bold; padding: 10px; margin-top: 20px; border-left: 5px solid #3498db; }
              </style>
            </head>
            <body>
              <h1>🛡️ Terraform Security Scan Executive Summary</h1>
              
              <div class="dashboard">
            `;

            tools.forEach(tool => {
              if (tool.data.findings.length === 0 && tool.data.counts.CRITICAL === 0) return;
              html += `
                <div class="card">
                  <h2>${tool.name}</h2>
                  <div class="severity"><span class="label">Critical</span> <span class="val CRITICAL">${tool.data.counts.CRITICAL}</span></div>
                  <div class="severity"><span class="label">High</span> <span class="val HIGH">${tool.data.counts.HIGH}</span></div>
                  <div class="severity"><span class="label">Medium</span> <span class="val MEDIUM">${tool.data.counts.MEDIUM}</span></div>
                  <div class="severity"><span class="label">Low</span> <span class="val LOW">${tool.data.counts.LOW}</span></div>
                </div>
              `;
            });

            html += `
              </div>

              <h2>Detailed Findings Consolidated</h2>
            `;

            tools.forEach(tool => {
              if (tool.data.findings.length === 0) return;

              // Sort findings by severity priority
              const sortedFindings = tool.data.findings.sort((a, b) => {
                const pa = severityPriority[a.severity] ?? 99;
                const pb = severityPriority[b.severity] ?? 99;
                return pa - pb;
              });

              html += `<div class="tool-header">${tool.name} Findings</div>`;
              html += `<table class="summary-table">
                <thead>
                  <tr>
                    <th style="width: 25%;">Resource</th>
                    <th style="width: 15%;">Severity</th>
                    <th>Description</th>
                  </tr>
                </thead>
                <tbody>`;
              
              sortedFindings.forEach(f => {
                html += `
                  <tr>
                    <td>${f.resource}</td>
                    <td><span class="${f.severity}">${f.severity}</span></td>
                    <td>${f.description}</td>
                  </tr>
                `;
              });

              html += `</tbody></table>`;
            });

            html += `
              <p style="text-align: center; margin-top: 30px;">For more technical details, please refer to the individual tool reports attached.</p>
              <div class="timestamp">Generated by GitHub Actions on ${new Date().toUTCString()}</div>
            </body>
            </html>
            `;

            fs.writeFileSync('summary.html', html);

            const browser = await chromium.launch();
            const page = await browser.newPage();
            const files = ['summary.html', 'trivy.html', 'tfsec.html', 'checkov.html'];

            for (const f of files) {
              if (!fs.existsSync(f)) continue;
              console.log('Rendering ' + f);
              await page.goto('file://' + process.cwd() + '/' + f);
              await page.waitForTimeout(3000);
              await page.pdf({ path: f.replace('.html', '.pdf'), format: 'A4', printBackground: true });
            }

            await browser.close();
          })();
          EOF

          node render.js

      # ---------- UPLOAD ----------
      - name: Upload PDF Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: terraform-security-pdf-reports
          path: '*.pdf'
