FROM python:3.11-slim

WORKDIR /app

COPY utilidades/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY utilidades/ .
RUN chmod +x generate_report.py

CMD ["python", "generate_report.py"]